
## Categories Routes...........
GET http://localhost:5000/categories

### Creating a Category
POST http://localhost:5000/categories
Content-Type: application/json

{
    "name":"Parathe",
    "description":"Flaky, stuffed flatbreads fried to perfection, a beloved North Indian cuisine staple with various delicious fillings."
}

### Get a category by id
GET http://localhost:5000/categories/64fddd41cd4767c497b359f2

### Update a category by id
PATCH  http://localhost:5000/categories/64f9a518292d0b5697fa7003
Content-Type: application/json

{   "name":"Chinese",
    "description":"Chinese Food"
}


### Delete a category by id
DELETE  http://localhost:5000/categories/64f975d7734b5534200613ba

### Invalid Url
GET http://localhost:5000/




## Recipes Routes...........
### Get all recipe of a specific category
GET http://localhost:5000/recipes/South Indian

### Creating a recipe
POST http://localhost:5000/recipes/South Indian
Content-Type: application/json

{
    "name":"Uttapam",
    "imageUrl":"/images",
    "description":"Uttapam is a popular South Indian breakfast or snack dish that is both delicious and wholesome. It is a type of dosa, but with a slightly thicker and spongy texture.",
    "rating":3,
    "c_id":"64fddd21cd4767c497b359f0",
    "category":"South Indian",
    "ratingCount":10,
    "isVeg":true,
    "ingredients":"1 cup rice*1/4 cup urad dal (black gram)*1/2 teaspoon fenugreek seeds*Salt to taste*Water for grinding*1/2 cup finely chopped onions*1/4 cup finely chopped tomatoes*2-3 green chilies, finely chopped*2 tablespoons chopped fresh coriander leaves*Cooking oil or ghee for making uttapam",
    "videoLink":"Rice, Urad Dal (Black Gram Lentils), Fenugreek Seeds, Water, Salt",
    "tags":"Dosa, South Indian, Indian Cuisine, Crepe, Pancake, Fermented Batter, Rice, Urad Dal, Fenugreek Seeds, Breakfast, Vegetarian, Masala Dosa, Cooking, Food, Culinary",
    "recipeMethod":"Soak rice, urad dal, and fenugreek seeds for 4-5 hours and poha for 10-15 minutes.*Grind rice, urad dal, and poha separately into smooth batters.*Mix the batters together, add salt, and let it ferment for 6-8 hours.*Heat a greased griddle and pour batter, spreading it into a thick pancake.*Sprinkle onions, tomatoes, green chilies, and coriander on top.*Cook with a lid on until the bottom turns golden brown.*Optionally flip and cook the other side.*Serve hot with chutney or sambar."
    
}

### Geting a single recipe by id
GET http://localhost:5000/recipes/about-recipe/64f9f7e069ce1ce1cd6f6b56


### update a recipe
PATCH http://localhost:5000/recipes/about-recipe/65329cdce76bb1b3f6997f69
Content-Type: application/json

{
    "name": "Idli",
    "imageUrl": "/idli"

}

### delete a recipe
DELETE http://localhost:5000/recipes/about-recipe/64f9f84a69ce1ce1cd6f6b59

### delete all recipe having a given c_idc(category)
DELETE http://localhost:5000/recipes/about-recipe/delete-all-recipe-by-category/64f998474cf3de0e7464be52

### update all recipe's category details by c_id
PATCH http://localhost:5000/recipes/about-recipe/update-all-recipe-by-category/64f998474cf3de0e7464be52
Content-Type: application/json

{
    "category": "North Indian"

}
