
## Categories Routes...........
GET http://localhost:5000/categories

### Creating a Category
POST http://localhost:5000/categories
Content-Type: application/json

{
    "name":"test food",
    "description":"West Indian food is very tasty"
}

### Get a category by id
GET http://localhost:5000/categories/64f975d7734b5534200613ba

### Update a category by id
PATCH  http://localhost:5000/categories/64f9a518292d0b5697fa7003
Content-Type: application/json

{   "name":"Chinese",
    "description":"Chinese Food"
}


### Delete a category by id
DELETE  http://localhost:5000/categories/64f9ea4ab762c8beab8ae63d

### Invalid Url
GET http://localhost:5000/




## Recipes Routes...........
### Get all recipe of a specific category
GET http://localhost:5000/recipes/South-Indian-Food

### Creating a recipe
POST http://localhost:5000/recipes/South-Indian-Food
Content-Type: application/json

{
    "name":"Noodles",
    "imageUrl":"/images",
    "description":"Dosa is a popular South Indian dish known for its thin, crispy texture and delicious flavor. It is a type of savory pancake or crepe made from a fermented batter primarily consisting of rice and urad dal (black gram lentils).",
    "rating":3,
    "c_id":"64f998474cf3de0e7464be52",
    "category":"Chinese",
    "ratingCount":10,
    "isVeg":true,
    "ingredients":"test food",
    "videoLink":"Rice, Urad Dal (Black Gram Lentils), Fenugreek Seeds, Water, Salt",
    "tags":"Dosa, South Indian, Indian Cuisine, Crepe, Pancake, Fermented Batter, Rice, Urad Dal, Fenugreek Seeds, Breakfast, Vegetarian, Masala Dosa, Cooking, Food, Culinary",
    "recipeMethod":"Wash and soak rice, urad dal, and fenugreek seeds in water for at least 4-6 hours.Drain the soaked ingredients and grind them into a smooth batter, adding water as needed.Add salt to the batter and mix well.Allow the batter to ferment for 6-8 hours or overnight, depending on the climate.Heat a non-stick skillet or griddle and grease it lightly with oil or ghee.Pour a ladleful of batter onto the hot skillet and spread it into a thin, circular shape.Cook until the dosa turns golden brown and crispy on one side.Optionally, flip the dosa and cook briefly on the other side.Remove from the skillet and serve hot with chutney, sambar, or your choice of filling."
    
}

### Geting a single recipe by id
GET http://localhost:5000/recipes/about-recipe/64f9f7e069ce1ce1cd6f6b56


### update a recipe
PATCH http://localhost:5000/recipes/about-recipe/64f9f84a69ce1ce1cd6f6b59
Content-Type: application/json

{
    "name": "Mendu Wada",
    "imageUrl": "/Mendu-wada"

}

### delete a recipe
DELETE http://localhost:5000/recipes/about-recipe/64f9f84a69ce1ce1cd6f6b59

### delete all recipe having a given c_idc(category)
DELETE http://localhost:5000/recipes/about-recipe/delete-all-recipe-by-category/64f998474cf3de0e7464be52

### update all recipe's category details by c_id
PATCH http://localhost:5000/recipes/about-recipe/update-all-recipe-by-category/64f998474cf3de0e7464be52
Content-Type: application/json

{
    "category": "North Indian"

}
